# Generated by Django 5.2.17 on 2026-09-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisment', '0001_initial'),
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='advertisement',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='advertisement_price_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='advertisement',
            constraint=models.CheckConstraint(condition=models.Q(('total_quantity__gt', 0)), name='advertisement_total_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='advertisement',
            constraint=models.CheckConstraint(condition=models.Q(('hold_quantity__gte', 0)), name='advertisement_hold_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='advertisement',
            constraint=models.CheckConstraint(condition=models.Q(('total_quantity__gte', models.F('hold_quantity'))), name='advertisement_total_quantity_gte_hold_quantity'),
        ),
    ]
