# Generated by Django 5.2.17 on 2026-09-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisment', '0002_advertisement_advertisement_price_gt_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
